export const FX_RATES_URL= "http://localhost:52698/api/fx";


export const RATES_HAS_ERRORED = 'RATES_HAS_ERRORED';
export const RATES_IS_LOADING = 'RATES_IS_LOADING';
export const RATES_FETCH_DATA_SUCCESS = 'RATES_FETCH_DATA_SUCCESS';
export const FILTER_RATES = 'FILTER_RATES';

export const ADDING_RATES = 'ADDING_RATES';
export const ADDING_RATES_SUCCESS = 'ADDING_RATES_SUCCESS';
export const APPEND_RATE_TO_EXISTING_RATES = 'APPEND_RATE_TO_EXISTING_RATES';
export const ADDING_RATES_ERRORED = 'ADDING_RATES_ERRORED';

export const SELECT_CURRENCY = 'SELECT_CURRENCY';